name: Deploy Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install
        working-directory: frontend

      - name: Gerar build
        run: npm run build
        working-directory: frontend

      - name: Enviar para Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.5
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          local_path: "./frontend/dist/*"
          remote_path: "/public_html/"
